INSERT INTO COMPANY(ID, COMPANY_ID, NAME) VALUES(1, 1, 'name1');
INSERT INTO COMPANY(ID, COMPANY_ID, NAME) VALUES(2, 15, '마이리얼트립');
INSERT INTO COMPANY(ID, COMPANY_ID, NAME) VALUES(3, 3, 'name3');

INSERT INTO JOB VALUES(1, 'img1', 1, 'position1', 2);
INSERT INTO JOB VALUES(2, 'img2', 2, 'position2', 2);